Pradumnasaraf/DevOps

Docker/commands/README.md

Host Port instead of Hot port.

docs: fix typo in `Docker/commands/README.md`

---

Docker/commands/README.md

Markdown missing ```

---

Docker/commands/README.md

I read through your notes, and I can assure you that they are quite beneficial. There are numerous typos that need to be addressed; I've already rectified a few and will keep doing so as I find more. Aslo Would you like if I add my cka preparation notes, tips and commands to this repository.

Fixing the typos

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/doc_issue.yaml
.github/ISSUE_TEMPLATE/feature.yaml
.github/ISSUE_TEMPLATE/other.yaml

- Add additional information field in all the issue forms.
- This is very useful when a user wants to provide additional information that doesn't fit any of the available fields.
- You might want to also add this field in your other repositories. :)

docs: add additional information field

---

Git/commands/README.md

DOCS! chnages to changes

---

Linux/commands/README.md

Fixed typos, and also corrected some commands in linux documentation

---

Linux/commands/README.md

fixed typos

---

Linux/commands/README.md

corrected command description

---

Docker/README.md
Go/App/ticket-booking/main.go
Go/Concepts/0) test.go
Go/Concepts/2) variables.go
Go/Concepts/7) slice.go
Go/README.md
Kubernetes/README.md
Linux/README.md
Networking/README.md
Prometheus/README.md
YAML/README.md
YAML/syntax/README.md

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/31"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix(docs): fix typos of a few sections

---

Jenkins/README.md

docs:removed the extra the

---

ArgoCD/README.md

- Fixed typo `Samle` to `Sample` in the cargo CD readme
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/33"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix: Typo Samle to Sample

---

Jenkins/README.md

correct the spelling of Jenkins 
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/37"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

correct the typo

---

GitHub-Actions/README.md

Corrected the spelling of "For"
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/40"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs:fixed the typo

---

Docker/commands/README.md

Fixed typos
Fixed some commands
Added some commands
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/42"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Modified Docker/README.md

---

GitOps/README.md

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/44"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added GitOps resource

---

Docker/README.md

Hi @Pradumnasaraf,
I've updated the docker networking section in README. 
This is how it looks after modification
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/47"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Updated Docker network in README

---

Docker/commands/README.md

Added the `docker image prune` command.
Prune is used to remove all unused images from your local registry.
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/55"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore: added `docker image prune` cmd

---

Docker/commands/README.md

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/52"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adding the command to delete all the images

---

Helm/README.md

issue resolve #49
- [x ] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.
I have just added the Helm free YouTube resources 
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/51"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Resolve #49 issue

---

Linux/commands/README.md

Fix a typo in the Linux notes.
Fix a typo in Linux notes when running two commands in one line.
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/58"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix typo in the linux notes

---

Go/Concepts/6) conversions.go

Added the code which demonstrates conversions in conversions.go file
**Before** ↓
**After** ↓
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/59"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added conversion code in DevOps\Go\Concepts\6) conversions.go

---

Git/commands/README.md

added new git command
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/62"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added new command

---

Bash-Scripting/README.md

Several Typo's Found in Bash-Scripting Readme.md
1) Line # 7 Learning Resources is Written as Lerning Resources. 
2) Line #72 , #74 : Arithmetic Word is Written as "Arthemetic
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/64"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Several Typo's Found in Bash-Scripting Readme.md

---

Bash-Scripting/README.md

Closes #63 
I deleted the additional occurrence of "the" in the line within the Bash-Scripting/README.md file.
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/65"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Update Bash-Scripting/README.md

---

ArgoCD/README.md

Fixed Typo's.
Closes #72 
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/73"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: correct typo in `ArgoCD/README.md`

---

Bash-Scripting/README.md

Updated the grammatical mistakes in the Basg scripting

Updated Bash-Scripting README.md

---

Kubernetes/commands/README.md

correct the spelling of scale
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/77"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

rectify the spelling

---

YAML/README.md

Closes #80 
Hi Pradumna, I have studied YAML from this source, it is more theoretical and contains examples but when you go through it, it really helps to understand the topic. Thank you.
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/81"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding a YAML learning resource

---

Linux/commands/README.md

#82 
Added a bulleted chunk for the `systemctl` command and also options that we could use to interact with process in Linux 
Please check the below screenshot to see the preview of the change.
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/83"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Addition of `systemctl` command in Linux directory in DevOps repo

---

Kubernetes/README.md

Added new Kubernetes Tutorial
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/84"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added new Kubernetes Tutorial

---

Docker/commands/README.md

docs: fix type

---

Docker/commands/README.md

close #87 
updating a new docker command for docker inside docker . for mounting the docker socket as a volume to the docker container for accessing the host's docker daemon to performing CI jenkins while using docker as agent.

Docker inside docker volume mount

---

GitHub-Actions/README.md

Closes #89 
- added `run` parameter 
- added `id` parameter to retrieve the output value

updated GitHub-Actions/README.md file

---

docusaurus.config.js
package-lock.json
package.json

Closes #94 
- Add Algolia search functionality

feat: add algolia search functionality

---

docs/golang/concepts/0) test.go
docs/golang/concepts/11) slices.go
docs/golang/concepts/12) slices2.go
docs/golang/concepts/13) map.go
docs/golang/concepts/20) methods.go
docs/golang/concepts/21) defer.go
docs/golang/concepts/22) map-ad.go
docs/golang/concepts/23) files.go
docs/golang/concepts/24) handling-web-req.go
docs/golang/concepts/26) http-requests.go
docs/golang/concepts/27) json.go
docs/golang/concepts/28) go-routine.go
docs/golang/concepts/30) waitgroup-api-eg.go
docs/golang/concepts/32) channels.go
docs/golang/concepts/33) channels-open.go
docs/golang/concepts/34) Interface.go
docs/golang/concepts/8) pointers.go
docs/golang/introduction.md

Again getting hands-on with Golang, and refreshing the memory, so will be updating the docs accordingly.

docs: Refactor Golang

---

README.md

PR updates the golang practice apps reference

fix: update golang practice apps reference

---

docs/yaml/tools.md

Closes #101 
Add a YAML resource to yaml/tools.md.
Yamline (https://yamline.com/), a collection of YAML tools.

[DOCS] Add a YAML resource to yaml/tools.md

---

docs/bash-scripting/introduction.md

Correct the code block Syntax in Bash Scripting

docs: correct the code block Syntax in Bash Scripting page

---

.github/workflows/vercel-preview.yml
.github/workflows/vercel-prod.yml
docs/terraform/introduction.md

- Improve Vercel's preview and production deployment

ci: Improve Vercel's preview and production deployment

---

docs/bash-scripting/learning-resources.md
docs/gitops/learning-resources.md
docs/introduction.md
docs/kubernetes/learning-resources.md
docs/terraform/learning-resources.md

This GitHub repo is a great resource! I've added some of my favorite learning resources to several sections.

Add learning resources
